import Head from 'next/head'
import Image from 'next/image'
import Paper from '@mui/material/Paper'
import Button from '@mui/material/Button'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/steam-express-logo.ico" />
      </Head>
      <div className={styles.container}>
        <main className={styles.main}>
          <Paper 
            style={{  
              backgroundImage: "url(" + "https://res.cloudinary.com/steam-express/image/upload/v1642249149/cld-sample.jpg" + ")",
              backgroundPosition: 'center',
              backgroundSize: 'cover',
              backgroundRepeat: 'no-repeat',
              alignItems: 'center',
            }}
            className="paperContainer"
          >

            <h1 className={styles.title}>
              Welcome aboard the STEAM Express!
            </h1>

            <p className={styles.description}>
              Start your{' '}
              <code className={styles.code}>STEAM Journey</code>
              today!
            </p>

            <Button href="/trial" className="homeTrialBtn">Book a Trial Class Now! &rarr;</Button>
          </Paper>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>
      </div>
    </>
  )
}
